bldg_dmg_dir: data/building_damage/
burned_area_dir: data/burned_area/
full_ignitions_file_path: data/yosemite_ignitions_firesize_100ac.csv
habitat_dmg_dir: data/habitat_damage/
intensity_dir: data/intensity/
prevention_file_path: data/prevention_table.csv
results_dir: results/prototype_run/
rx_burn_units_path: data/rx_burn/RX_Burn_Units.shp
values_file_path: data/values_table.csv
intensity_dir: data/intensity/
budget: 
- 10
- 15
- 20